---
abstract: 'Display a stack trace on the debug screen'
author:
  - 'Andy Grundman, <andy@hybridized.org>'
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Plugin-StackTrace
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst: 5.70
  Devel::StackTrace: 0
  MRO::Compat: 0.10
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.10
