---
name: Catalyst-Plugin-StackTrace
version: 0.03
author: ~
abstract: Display a stack trace on the debug screen
license: perl
requires:
  Catalyst: 5.61
  Devel::StackTrace: 0
provides:
  Catalyst::Plugin::StackTrace:
    file: lib/Catalyst/Plugin/StackTrace.pm
    version: 0.03
generated_by: Module::Build version 0.2611
