---
abstract: 'Display a stack trace on the debug screen'
author:
  - 'Andy Grundman, <andy@hybridized.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Plugin-StackTrace
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst: 5.70
  Devel::StackTrace: 0
  MRO::Compat: 0.10
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: http://dev.catalyst.perl.org/repos/Catalyst/trunk/Catalyst-Plugin-StackTrace/
version: 0.12
